#
# File name: Dockerfile_pattern
# Description: Dockerfile which builds the Webash api's image
# Authors: colivier74
# If you're a new WeBash contributor and worked on this file, please add your name here.
#
# This file is part of the WeBash project with is released under the terms of GNU General Public License V3.0.
# You should have received a copy of the GNU General Public License along with WeBash. If not, see <https://www.gnu.org/licenses/>.
#

FROM node:latest
MAINTAINER Olivier Cartier <colivier.dev@gmail.com>

WORKDIR /app
COPY package.json /app
RUN npm install

COPY server.js /app
COPY res /app/res
COPY README.md /app

EXPOSE 80
CMD [ "npm", "start" ]
