version: '3'
services:
  api:
    container_name: "${NAME}"
    restart: always
    build: .
    env_file:
      - .env
    ports:
     - "${PORT}:80"
    networks:
      net:
        ipv4_address: "${IP}"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"