#
# File name: Dockerfile_pattern
# Description: Create a docker container with the Dockerfile et the variables of the .env file
# Authors: colivier74
# If you're a new WeBash contributor and worked on this file, please add you name here.
#
# This file is part of the WeBash project with is released under the terms of GNU General Public License V3.0.
# You should have recieved a copy of it along with this file, if not, please write to :
# Free Software Foundation, Inc., 51 Franklin Street, Fifth floor, Boston, MA 02110-1301 USA.
#

version: '3'
services:
  api:
    container_name: "${NAME}"
    restart: always
    build: .
    env_file:
      - .env
    ports:
     - "${PORT}:80"
    networks:
      net:
        ipv4_address: "${IP}"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"