#
# File name: Dockerfile_pattern
# Description: TODO
# Authors: colivier74
# If you're a new WeBash contributor and worked on this file, please add you name here.
#
# This file is part of the WeBash project with is released under the terms of GNU General Public License V3.0.
# You should have recieved a copy of it along with this file, if not, please write to :
# Free Software Foundation, Inc., 51 Franklin Street, Fifth floor, Boston, MA 02110-1301 USA.
#

FROM node:latest
MAINTAINER Olivier Cartier <colivier.dev@gmail.com>

WORKDIR /app
COPY package.json /app
RUN npm install

COPY server.js /app
COPY res /app/res
COPY README.md /app

EXPOSE 80
CMD [ "npm", "start" ]
